services:
    Google_Client:
        class: Google_Client
        calls:
            - [setAuthConfig, ['%kernel.project_dir%%env(GOOGLE_CREDENTIALS)%']]
            - [setApplicationName, ['%env(GOOGLE_APP_NAME)%']]
            - [setAccessType, ['offline']]
